export const actions = {
  GET_TASKS: "GET_TASKS",
  UPDATE_TASK: "UPDATE_TASK",
  DELETE_TASK: "DELETE_TASK",
  SET_SEARCH: "SET_SEARCH",
  SET_IS_MODAL_OPEN: "SET_IS_MODAL_OPEN",
  TOGGLE_SHOW_OWN_TASKS: "TOGGLE_SHOW_OWN_TASKS",
  TOGGLE_SHOW_FLAGGED_TASKS: "TOGGLE_SHOW_FLAGGED_TASKS",
  SET_TASK_TO_UPDATE: "SET_TASK_TO_UPDATE",
};
